# Generated by Django 5.0.1 on 2024-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('value', models.TextField()),
                ('unit', models.TextField()),
                ('name', models.TextField()),
                ('search_time', models.DateTimeField()),
            ],
        ),
    ]
