// This file contains constants used in the analytics module of the Focus Bear application.

const COLUMN_NAME_MAPPING = {
    USER_ID: "Userid",
    TEAM_ID: "Team ID",
    FIRST_DESKTOP_LOGIN_DATE: "First desktop login date",
    LAST_UPDATED_DATE: "Last updated date",
    SUBSCRIPTION_STATUS: "Subscription Status",
    PERCENT_DAYS_DID_MORNING_ROUTINE: "% of days since signup did morning routine habit",
    PERCENT_DAYS_DID_EVENING_ROUTINE: "% of days since signup did evening routine habit",
    PERCENT_DAYS_DID_BREAK_ROUTINE: "% of days since signup did break habit",
    PERCENT_DAYS_DID_FOCUS_SESSION: "% of days since signup did focus session",
    DID_ACTIVE: "Did activate",
    AVERAGE_HOURS_DEEP_WORK_PER_WEEK: "Average hours of deep work per week",
    NUMBER_MORNING_ROUTINE_HABITS: "Number of morning routine habits",
    NUMBER_EVENING_ROUTINE_HABITS: "Number of evening routine habits",
    NUMBER_BREAK_HABITS: "Number of break habits",
    NUMBER_OF_FOCUS_MODE: "Number of focus modes",
    SATISFACTION_WITH_BREAK_TIMING: "Satisfaction with break timing",
    COMPLETED_MENU_TOUR: "Completed menu tour",
    STARTED_BREAK_ACTIVITY: "Started a break activity",
    COMPLETED_BREAK_ACTIVITY: "Completed a break activity",
    STARTED_MORNING_ROUTINE: "Started morning routine",
    COMPLETED_MORNING_ROUTINE: "Completed a morning routine",
    STARTED_EVENING_ROUTINE: "Started evening routine",
    COMPLETED_EVENING_ROUTINE: "Completed an evening routine",
    STARTED_FOCUS_MODE: "Started focus mode",
    STARTED_POMODORO: "Started pomodoro",
    SWITCH_TO_GEEK_MODE: "Switched to geek mode",
    SWITCH_TO_SIMPLE_MODE: "Switched to simple mode",
    BLOCKED_AN_APP: "Blocked an app",
    BLOCKED_A_URL: "Blocked a url",
    BLOCKED_ON_MOBILE: "Blocked on mobile",
    SIGNED_UP_ON_MOBILE: "Signed Up on mobile",
    SIGNED_UP_ON_MOBILE_DATE: "Signed Up on mobile Date",
    COMMITMENT_LEVEL_FOR_HABITS: "Commitment level for habits",
    CARE_FACTOR_FOR_BREAKS: "Care factor for breaks",
    DID_MORNING_HABIT_ON_DAY_1: "Did morning habits on day 1",
    USED_BREAKS_ON_DAY_1: "Used breaks on day 1",
    USED_FOCUS_MODE_ON_DAY_1: "Used focus mode on day 1",
    DID_EVENING_HABIT_ON_DAY_1: "Did evening habits on day 1",
    DID_MORNING_HABIT_ON_DAY_2: "Did morning habits on day 2",
    USED_BREAKS_ON_DAY_2: "Used breaks on day 2",
    USED_FOCUS_MODE_ON_DAY_2: "Used focus mode on day 2",
    DID_EVENING_HABIT_ON_DAY_2: "Did evening habits on day 2",
    DID_MORNING_HABIT_ON_DAY_3: "Did morning habits on day 3",
    USED_BREAKS_ON_DAY_3: "Used breaks on day 3",
    USED_FOCUS_MODE_ON_DAY_3: "Used focus mode on day 3",
    DID_EVENING_HABIT_ON_DAY_3: "Did evening habits on day 3",
    DID_MORNING_HABIT_ON_DAY_4: "Did morning habits on day 4",
    USED_BREAKS_ON_DAY_4: "Used breaks on day 4",
    USED_FOCUS_MODE_ON_DAY_4: "Used focus mode on day 4",
    DID_EVENING_HABIT_ON_DAY_4: "Did evening habits on day 4",
    DID_MORNING_HABIT_ON_DAY_5: "Did morning habits on day 5",
    USED_BREAKS_ON_DAY_5: "Used breaks on day 5",
    USED_FOCUS_MODE_ON_DAY_5: "Used focus mode on day 5",
    DID_EVENING_HABIT_ON_DAY_5: "Did evening habits on day 5",
    DID_MORNING_HABIT_ON_DAY_6: "Did morning habits on day 6",
    USED_BREAKS_ON_DAY_6: "Used breaks on day 6",
    USED_FOCUS_MODE_ON_DAY_6: "Used focus mode on day 6",
    DID_EVENING_HABIT_ON_DAY_6: "Did evening habits on day 6",
    DID_MORNING_HABIT_ON_DAY_7: "Did morning habits on day 7",
    USED_BREAKS_ON_DAY_7: "Used breaks on day 7",
    USED_FOCUS_MODE_ON_DAY_7: "Used focus mode on day 7",
    DID_EVENING_HABIT_ON_DAY_7: "Did evening habits on day 7",
    DID_MORNING_HABIT_ON_DAY_8: "Did morning habits on day 8",
    USED_BREAKS_ON_DAY_8: "Used breaks on day 8",
    USED_FOCUS_MODE_ON_DAY_8: "Used focus mode on day 8",
    DID_EVENING_HABIT_ON_DAY_8: "Did evening habits on day 8",
    DID_MORNING_HABIT_ON_DAY_9: "Did morning habits on day 9",
    USED_BREAKS_ON_DAY_9: "Used breaks on day 9",
    USED_FOCUS_MODE_ON_DAY_9: "Used focus mode on day 9",
    DID_EVENING_HABIT_ON_DAY_9: "Did evening habits on day 9",
    DID_MORNING_HABIT_ON_DAY_10: "Did morning habits on day 10",
    USED_BREAKS_ON_DAY_10: "Used breaks on day 10",
    USED_FOCUS_MODE_ON_DAY_10: "Used focus mode on day 10",
    DID_EVENING_HABIT_ON_DAY_10: "Did evening habits on day 10",
    DID_MORNING_HABIT_ON_DAY_11: "Did morning habits on day 11",
    USED_BREAKS_ON_DAY_11: "Used breaks on day 11",
    USED_FOCUS_MODE_ON_DAY_11: "Used focus mode on day 11",
    DID_EVENING_HABIT_ON_DAY_11: "Did evening habits on day 11",
    DID_MORNING_HABIT_ON_DAY_12: "Did morning habits on day 12",
    USED_BREAKS_ON_DAY_12: "Used breaks on day 12",
    USED_FOCUS_MODE_ON_DAY_12: "Used focus mode on day 12",
    DID_EVENING_HABIT_ON_DAY_12: "Did evening habits on day 12",
    DID_MORNING_HABIT_ON_DAY_13: "Did morning habits on day 13",
    USED_BREAKS_ON_DAY_13: "Used breaks on day 13",
    USED_FOCUS_MODE_ON_DAY_13: "Used focus mode on day 13",
    DID_EVENING_HABIT_ON_DAY_13: "Did evening habits on day 13",
    DID_MORNING_HABIT_ON_DAY_14: "Did morning habits on day 14",
    USED_BREAKS_ON_DAY_14: "Used breaks on day 14",
    USED_FOCUS_MODE_ON_DAY_14: "Used focus mode on day 14",
    DID_EVENING_HABIT_ON_DAY_14: "Did evening habits on day 14",
    DID_MORNING_HABIT_ON_DAY_15: "Did morning habits on day 15",
    USED_BREAKS_ON_DAY_15: "Used breaks on day 15",
    USED_FOCUS_MODE_ON_DAY_15: "Used focus mode on day 15",
    DID_EVENING_HABIT_ON_DAY_15: "Did evening habits on day 15",
    DID_MORNING_HABIT_ON_DAY_16: "Did morning habits on day 16",
    USED_BREAKS_ON_DAY_16: "Used breaks on day 16",
    USED_FOCUS_MODE_ON_DAY_16: "Used focus mode on day 16",
    DID_EVENING_HABIT_ON_DAY_16: "Did evening habits on day 16",
    DID_MORNING_HABIT_ON_DAY_17: "Did morning habits on day 17",
    USED_BREAKS_ON_DAY_17: "Used breaks on day 17",
    USED_FOCUS_MODE_ON_DAY_17: "Used focus mode on day 17",
    DID_EVENING_HABIT_ON_DAY_17: "Did evening habits on day 17",
    DID_MORNING_HABIT_ON_DAY_18: "Did morning habits on day 18",
    USED_BREAKS_ON_DAY_18: "Used breaks on day 18",
    USED_FOCUS_MODE_ON_DAY_18: "Used focus mode on day 18",
    DID_EVENING_HABIT_ON_DAY_18: "Did evening habits on day 18",
    DID_MORNING_HABIT_ON_DAY_19: "Did morning habits on day 19",
    USED_BREAKS_ON_DAY_19: "Used breaks on day 19",
    USED_FOCUS_MODE_ON_DAY_19: "Used focus mode on day 19",
    DID_EVENING_HABIT_ON_DAY_19: "Did evening habits on day 19",
    DID_MORNING_HABIT_ON_DAY_20: "Did morning habits on day 20",
    USED_BREAKS_ON_DAY_20: "Used breaks on day 20",
    USED_FOCUS_MODE_ON_DAY_20: "Used focus mode on day 20",
    DID_EVENING_HABIT_ON_DAY_20: "Did evening habits on day 20",
    DID_MORNING_HABIT_ON_DAY_21: "Did morning habits on day 21",
    USED_BREAKS_ON_DAY_21: "Used breaks on day 21",
    USED_FOCUS_MODE_ON_DAY_21: "Used focus mode on day 21",
    DID_EVENING_HABIT_ON_DAY_21: "Did evening habits on day 21",
    DID_MORNING_HABIT_ON_DAY_22: "Did morning habits on day 22",
    USED_BREAKS_ON_DAY_22: "Used breaks on day 22",
    USED_FOCUS_MODE_ON_DAY_22: "Used focus mode on day 22",
    DID_EVENING_HABIT_ON_DAY_22: "Did evening habits on day 22",
    DID_MORNING_HABIT_ON_DAY_23: "Did morning habits on day 23",
    USED_BREAKS_ON_DAY_23: "Used breaks on day 23",
    USED_FOCUS_MODE_ON_DAY_23: "Used focus mode on day 23",
    DID_EVENING_HABIT_ON_DAY_23: "Did evening habits on day 23",
    DID_MORNING_HABIT_ON_DAY_24: "Did morning habits on day 24",
    USED_BREAKS_ON_DAY_24: "Used breaks on day 24",
    USED_FOCUS_MODE_ON_DAY_24: "Used focus mode on day 24",
    DID_EVENING_HABIT_ON_DAY_24: "Did evening habits on day 24",
    DID_MORNING_HABIT_ON_DAY_25: "Did morning habits on day 25",
    USED_BREAKS_ON_DAY_25: "Used breaks on day 25",
    USED_FOCUS_MODE_ON_DAY_25: "Used focus mode on day 25",
    DID_EVENING_HABIT_ON_DAY_25: "Did evening habits on day 25",
    DID_MORNING_HABIT_ON_DAY_26: "Did morning habits on day 26",
    USED_BREAKS_ON_DAY_26: "Used breaks on day 26",
    USED_FOCUS_MODE_ON_DAY_26: "Used focus mode on day 26",
    DID_EVENING_HABIT_ON_DAY_26: "Did evening habits on day 26",
    DID_MORNING_HABIT_ON_DAY_27: "Did morning habits on day 27",
    USED_BREAKS_ON_DAY_27: "Used breaks on day 27",
    USED_FOCUS_MODE_ON_DAY_27: "Used focus mode on day 27",
    DID_EVENING_HABIT_ON_DAY_27: "Did evening habits on day 27",
    DID_MORNING_HABIT_ON_DAY_28: "Did morning habits on day 28",
    USED_BREAKS_ON_DAY_28: "Used breaks on day 28",
    USED_FOCUS_MODE_ON_DAY_28: "Used focus mode on day 28",
    DID_EVENING_HABIT_ON_DAY_28: "Did evening habits on day 28",
    OCCUPATION: "Occupation",
    ENABLE_TIME_TRACKER: "Enabled Time Tracker",
    ENABLE_LATE_NO_MORE: "Enabled Late No More",
    QUIT_WITHIN_7_DAYS: "Quit within 7 days",
    GOALS_FOR_FOCUS_BEAR: "Hopes for using Focus Bear",
    UNINSTALLED_APP: "Uninstalled app",
  };
  
  const eventTypeConstant = {
    USER_ID: "user_id",
    LOGIN_HOMEMADE: "login-homemade",
    UPDATED_AT: "updated_at",
    REVENUE_CAT_STATUS: "revenue_cat_status",
    COMPLETE_MORNING_ROUTINE_ACTIVITY: "complete-morning-routine-activity",
    COMPLETE_EVENING_ROUTINE_ACTIVITY: "complete-evening-routine-activity",
    COMPLETE_BREAK_ACTIVITY: "complete-break-activity",
    START_POMODORO_MODE_MANUALLY: "start-pomodoro-mode-manually",
    START_FOCUS_MODE_MANUALLY: "start-focus-mode-manually",
    COMPLETED_FOCUS_SESSION: "completed-focus-session",
    MORNING: "morning",
    EVENING: "evening",
    BREAKING: "breaking",
    FOCUS_MODE: "focus-mode",
    BREAK_FEEDBACK_LEFT: "break-feedback-left",
    MENU_TOUR_SETUP_COMPLETE: "menu_tour_setup_complete",
    START_BREAK_ACTIVITY: "start-break-activity",
    START_MORNING_ROUTINE: "start-morning-routine",
    COMPLETE_MORNING_ROUTINE: "complete-morning-routine",
    START_EVENING_ROUTINE: "start-evening-routine",
    COMPLETE_EVENING_ROUTINE: "complete-evening-routine",
    SWITCH_TO_GEEK_MODE: "switch-to-geek-mode",
    SWITCH_TO_SIMPLE_MODE: "switch-to-simple-mode",
    BLOCK_DISTRACTING_APP: "block-distracting-app",
    BLOCK_DISTRACTING_URL: "block-distracting-url",
    BLOCK_DISTRACTION: "block-distraction",
    SIGNUP: "signup",
    CARE_ABOUT_HABITS: "care-about-habits",
    CARE_ABOUT_BREAKS: "cares-about-breaks",
    OCCUPATION_SELECTED: "occupation-selected",
    SETTING_CHANGED_ENABLE_TIME_TRACKER: "settings-changed-enable-time-tracker",
    SHOW_LATE_NO_MORE_WINDOW: "show-latenomore-window",
    APP_QUIT: "app-quit",
    LOGIN: "login",
    GOALS_FOR_FOCUS_BEAR: "custom-goal-selected",
    UNINSTALL: "uninstall",
  };
  
  const breakDownByPropertyConstant = {
    COUNT: "count",
    EVENT_COUNT: "eventCount",
    COUNT_WITH_MULTIPLE_TYPES: "count_with_multiple_types",
  };
  
  const highlightRuleConstant = {
    RED: "red",
    GREEN: "green",
  };
  
  // OS Names
  const WEB_OPERATION_SYSTEM = "Web";
  const IOS_OPERATION_SYSTEM = "iOS";
  const MACOS_OPERATION_SYSTEM = "MacOS";
  const WINDOWS_OPERATION_SYSTEM = "Windows";
  const ANDROID_OPERATION_SYSTEM = "Android";
  const UNKNOWN_OPERATING_SYSTEM = "Unknown";
  const ANDROID_DEVICE_NAME = "okhttp"; // Used for OS detection
  
  // Auth0 Client IDs
  const MAC_CLIENT_ID = "dgMrlNC5mM634Sxi9SLqIqi0WvgVpwX7";
  const WINDOWS_CLIENT_ID = "YAYPDa7sAVKuheZy3dYWyzNncOSZq98I";
  const MOBILE_CLIENT_ID = [
    "cZ2J5dR8FliHiTyOdlyk18wKottWxPaC",
    "9hhQ3ymKQQsrAHkHlrVYzMPoJ9VZqrJ8",
  ];
  
  // Report Configuration Array (used in report generation)
  const reportConfig = [
    { excel_column_name: COLUMN_NAME_MAPPING.USER_ID, event_type: eventTypeConstant.USER_ID, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.TEAM_ID, event_type: 'user_data_team_id', highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.FIRST_DESKTOP_LOGIN_DATE, event_type: eventTypeConstant.LOGIN_HOMEMADE, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.LAST_UPDATED_DATE, event_type: eventTypeConstant.UPDATED_AT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.OCCUPATION, event_type: eventTypeConstant.OCCUPATION_SELECTED, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SUBSCRIPTION_STATUS, event_type: eventTypeConstant.REVENUE_CAT_STATUS, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.GOALS_FOR_FOCUS_BEAR, event_type: eventTypeConstant.GOALS_FOR_FOCUS_BEAR, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.UNINSTALLED_APP, event_type: eventTypeConstant.UNINSTALL, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.PERCENT_DAYS_DID_MORNING_ROUTINE, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.PERCENT_DAYS_DID_EVENING_ROUTINE, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.PERCENT_DAYS_DID_BREAK_ROUTINE, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.PERCENT_DAYS_DID_FOCUS_SESSION, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.DID_ACTIVE, event_type: `${eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY},${eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY},${eventTypeConstant.COMPLETE_BREAK_ACTIVITY},${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.COUNT_WITH_MULTIPLE_TYPES, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.AVERAGE_HOURS_DEEP_WORK_PER_WEEK, event_type: eventTypeConstant.COMPLETED_FOCUS_SESSION, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.NUMBER_MORNING_ROUTINE_HABITS, event_type: eventTypeConstant.MORNING, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.NUMBER_EVENING_ROUTINE_HABITS, event_type: eventTypeConstant.EVENING, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.NUMBER_BREAK_HABITS, event_type: eventTypeConstant.BREAKING, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.NUMBER_OF_FOCUS_MODE, event_type: eventTypeConstant.FOCUS_MODE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SATISFACTION_WITH_BREAK_TIMING, event_type: eventTypeConstant.BREAK_FEEDBACK_LEFT, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.COMPLETED_MENU_TOUR, event_type: eventTypeConstant.MENU_TOUR_SETUP_COMPLETE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.STARTED_BREAK_ACTIVITY, event_type: eventTypeConstant.START_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.COMPLETED_BREAK_ACTIVITY, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.STARTED_MORNING_ROUTINE, event_type: eventTypeConstant.START_MORNING_ROUTINE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.COMPLETED_MORNING_ROUTINE, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.STARTED_EVENING_ROUTINE, event_type: eventTypeConstant.START_EVENING_ROUTINE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.COMPLETED_EVENING_ROUTINE, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.STARTED_FOCUS_MODE, event_type: eventTypeConstant.START_FOCUS_MODE_MANUALLY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.STARTED_POMODORO, event_type: eventTypeConstant.START_POMODORO_MODE_MANUALLY, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SWITCH_TO_GEEK_MODE, event_type: eventTypeConstant.SWITCH_TO_GEEK_MODE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SWITCH_TO_SIMPLE_MODE, event_type: eventTypeConstant.SWITCH_TO_SIMPLE_MODE, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.BLOCKED_AN_APP, event_type: eventTypeConstant.BLOCK_DISTRACTING_APP, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.BLOCKED_A_URL, event_type: eventTypeConstant.BLOCK_DISTRACTING_URL, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.BLOCKED_ON_MOBILE, event_type: eventTypeConstant.BLOCK_DISTRACTION, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SIGNED_UP_ON_MOBILE, event_type: eventTypeConstant.SIGNUP, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.SIGNED_UP_ON_MOBILE_DATE, event_type: eventTypeConstant.SIGNUP, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.COMMITMENT_LEVEL_FOR_HABITS, event_type: eventTypeConstant.CARE_ABOUT_HABITS, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.CARE_FACTOR_FOR_BREAKS, event_type: eventTypeConstant.CARE_ABOUT_BREAKS, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_1, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 0, endHours: 24, },
    { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_1, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 0, endHours: 24, },
    { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_1, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 0, endHours: 24, },
    { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_1, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 0, endHours: 24, },
    
    // Day 2
    { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_2, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 25, endHours: 48, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_2, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 25, endHours: 48, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_2, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 25, endHours: 48, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_2, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 25, endHours: 48, },
  // --- Day 3 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_3, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 49, endHours: 72, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_3, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 49, endHours: 72, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_3, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 49, endHours: 72, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_3, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 49, endHours: 72, },
  // --- Day 4 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_4, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 73, endHours: 96, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_4, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 73, endHours: 96, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_4, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 73, endHours: 96, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_4, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 73, endHours: 96, },
  // --- Day 5 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_5, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 97, endHours: 120, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_5, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 97, endHours: 120, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_5, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 97, endHours: 120, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_5, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 97, endHours: 120, },
  // --- Day 6 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_6, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 121, endHours: 144, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_6, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 121, endHours: 144, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_6, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 121, endHours: 144, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_6, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 121, endHours: 144, },
  // --- Day 7 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_7, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 145, endHours: 168, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_7, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 145, endHours: 168, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_7, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 145, endHours: 168, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_7, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 145, endHours: 168, },
  // --- Day 8 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_8, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 169, endHours: 192, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_8, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 169, endHours: 192, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_8, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 169, endHours: 192, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_8, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 169, endHours: 192, },
  // --- Day 9 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_9, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 193, endHours: 216, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_9, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 193, endHours: 216, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_9, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 193, endHours: 216, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_9, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 193, endHours: 216, },
  // --- Day 10 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_10, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 217, endHours: 240, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_10, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 217, endHours: 240, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_10, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 217, endHours: 240, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_10, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 217, endHours: 240, },
  // --- Day 11 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_11, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 241, endHours: 264, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_11, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 241, endHours: 264, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_11, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 241, endHours: 264, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_11, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 241, endHours: 264, },
  // --- Day 12 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_12, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 265, endHours: 288, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_12, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 265, endHours: 288, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_12, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 265, endHours: 288, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_12, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 265, endHours: 288, },
  // --- Day 13 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_13, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 289, endHours: 312, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_13, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 289, endHours: 312, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_13, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 289, endHours: 312, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_13, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 289, endHours: 312, },
  // --- Day 14 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_14, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 313, endHours: 336, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_14, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 313, endHours: 336, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_14, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 313, endHours: 336, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_14, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 313, endHours: 336, },
  // --- Day 15 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_15, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 337, endHours: 360, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_15, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 337, endHours: 360, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_15, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 337, endHours: 360, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_15, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 337, endHours: 360, },
  // --- Day 16 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_16, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 361, endHours: 384, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_16, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 361, endHours: 384, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_16, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 361, endHours: 384, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_16, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 361, endHours: 384, },
  // --- Day 17 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_17, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 385, endHours: 408, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_17, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 385, endHours: 408, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_17, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 385, endHours: 408, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_17, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 385, endHours: 408, },
  // --- Day 18 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_18, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 409, endHours: 432, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_18, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 409, endHours: 432, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_18, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 409, endHours: 432, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_18, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 409, endHours: 432, },
  // --- Day 19 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_19, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 433, endHours: 456, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_19, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 433, endHours: 456, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_19, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 433, endHours: 456, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_19, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 433, endHours: 456, },
  // --- Day 20 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_20, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 457, endHours: 480, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_20, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 457, endHours: 480, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_20, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 457, endHours: 480, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_20, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 457, endHours: 480, },
  // --- Day 21 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_21, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 481, endHours: 504, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_21, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 481, endHours: 504, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_21, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 481, endHours: 504, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_21, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 481, endHours: 504, },
  // --- Day 22 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_22, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 505, endHours: 528, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_22, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 505, endHours: 528, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_22, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 505, endHours: 528, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_22, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 505, endHours: 528, },
  // --- Day 23 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_23, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 529, endHours: 552, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_23, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 529, endHours: 552, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_23, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 529, endHours: 552, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_23, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 529, endHours: 552, },
  // --- Day 24 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_24, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 553, endHours: 576, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_24, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 553, endHours: 576, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_24, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 553, endHours: 576, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_24, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 553, endHours: 576, },
  // --- Day 25 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_25, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 577, endHours: 600, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_25, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 577, endHours: 600, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_25, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 577, endHours: 600, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_25, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 577, endHours: 600, },
  // --- Day 26 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_26, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 601, endHours: 624, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_26, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 601, endHours: 624, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_26, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 601, endHours: 624, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_26, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 601, endHours: 624, },
  // --- Day 27 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_27, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 625, endHours: 648, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_27, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 625, endHours: 648, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_27, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 625, endHours: 648, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_27, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 625, endHours: 648, },
  // --- Day 28 --- 
  { excel_column_name: COLUMN_NAME_MAPPING.DID_MORNING_HABIT_ON_DAY_28, event_type: eventTypeConstant.COMPLETE_MORNING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 649, endHours: 672, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_BREAKS_ON_DAY_28, event_type: eventTypeConstant.COMPLETE_BREAK_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 649, endHours: 672, },
  { excel_column_name: COLUMN_NAME_MAPPING.USED_FOCUS_MODE_ON_DAY_28, event_type: `${eventTypeConstant.START_POMODORO_MODE_MANUALLY},${eventTypeConstant.START_FOCUS_MODE_MANUALLY}`, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 649, endHours: 672, },
  { excel_column_name: COLUMN_NAME_MAPPING.DID_EVENING_HABIT_ON_DAY_28, event_type: eventTypeConstant.COMPLETE_EVENING_ROUTINE_ACTIVITY, breakDownByProperty: breakDownByPropertyConstant.EVENT_COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", startHours: 649, endHours: 672, },
    // End Day X
    { excel_column_name: COLUMN_NAME_MAPPING.ENABLE_TIME_TRACKER, event_type: eventTypeConstant.SETTING_CHANGED_ENABLE_TIME_TRACKER, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.ENABLE_LATE_NO_MORE, event_type: eventTypeConstant.SHOW_LATE_NO_MORE_WINDOW, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
    { excel_column_name: COLUMN_NAME_MAPPING.QUIT_WITHIN_7_DAYS, event_type: eventTypeConstant.APP_QUIT, breakDownByProperty: breakDownByPropertyConstant.COUNT, highlightRule: "", timeframe: { offset: "", offsetDays: "" }, value: "", },
  ];
  
  
  module.exports = {
      // Export all constants
      COLUMN_NAME_MAPPING,
      eventTypeConstant,
      breakDownByPropertyConstant,
      highlightRuleConstant,
      reportConfig, // Export the report config array
      // OS Names
      WEB_OPERATION_SYSTEM,
      IOS_OPERATION_SYSTEM,
      MACOS_OPERATION_SYSTEM,
      WINDOWS_OPERATION_SYSTEM,
      ANDROID_OPERATION_SYSTEM,
      UNKNOWN_OPERATING_SYSTEM,
      ANDROID_DEVICE_NAME,
      // Auth0 Client IDs
      MAC_CLIENT_ID,
      WINDOWS_CLIENT_ID,
      MOBILE_CLIENT_ID,
  };
  
  // --- END OF FILE config/constants.js ---